const ActionTypes = {
    EDITOR: {
        CREATE: 'EDITOR.CREATE',
        DROP_NEW_MODEL: 'EDITOR.DROP_NEW_MODEL',
        ADD_NEW_MODEL: 'EDITOR.ADD_NEW_MODEL',
        ELEMENT_RIGHT_CLICKED: 'EDITOR.ELEMENT_RIGHT_CLICKED',
        ELEMENT_DOUBLE_CLICKED: 'EDITOR.ELEMENT_DOUBLE_CLICKED',
        ELEMENT_DELETE: 'EDITOR.ELEMENT_DELETE',
        ELEMENT_CANCEL: 'EDITOR.ELEMENT_CANCEL',
        ELEMENT_SAVE: 'EDITOR.ELEMENT_SAVE',
        ELEMENT_LABEL_EDIT: 'EDITOR.ELEMENT_LABEL_EDIT',
        ELEMENT_CHANGE_X: 'EDITOR.ELEMENT_CHANGE_X',
        ELEMENT_CHANGE_Y: 'EDITOR.ELEMENT_CHANGE_Y',
        TOOL_ELEMENT_CLICKED: 'EDITOR.TOOL_ELEMENT_CLICKED',
        TOOL_ELEMENT_RELEASED: 'EDITOR.TOOL_ELEMENT_RELEASED',
        TOOL_TAB_SELECTED: 'EDITOR.TOOL_TAB_SELECTED'
    }
}

export default ActionTypes;
